Controllers/RideReservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ridewithme.Models;

namespace Ridewithme.Controllers
{
    [Authorize]
    public class RideReservationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: RideReservations
        public ActionResult Index()
        {
            return View(db.RideReservations.ToList());
        }
#pragma warning disable CS0108 // Member hides inherited member; missing new keyword

        [Authorize(Roles = "Driver")]
        public ActionResult Request(string driver)
#pragma warning restore CS0108 // Member hides inherited member; missing new keyword
        {
            var request = db.RideReservations.Where(x => x.DriverName == driver).ToList();
            return View(request);
        }
        [Authorize(Roles = "Passenger")]
        public ActionResult Status(string passenger)
        {
            var status = db.RideReservations.Where(x => x.PassengerName == passenger).ToList();
            return View(status);
        }

        public string DriverDetails(int? id)
        {
            string contact = "";
            var reservation = db.RideReservations.Find(id);
            if(reservation!=null)
            {
                var driver = db.Rides.Where(x => x.UserName == reservation.DriverName).FirstOrDefault();
                if(driver!=null)
                {
                    contact = driver.ContactNumber;
                }
            }
            return contact;
        }
        [Authorize(Roles = "Driver")]
        public ActionResult Accept(int? id, int seats)
        {
            string name = "";
            var result = db.RideReservations.SingleOrDefault(m => m.ReservationID == id);
            if (result != null)
            {
                name = result.DriverName;
                var result3 = db.Rides.SingleOrDefault(m => m.RideID == result.RideID);
                if (result3 != null)
                {
                    if(result3.AvailableSeats !=0)
                    {
                        result.ReservationStatus = "Accepted";
                        db.SaveChanges();
                        var result2 = db.Rides.SingleOrDefault(m => m.RideID == result.RideID);
                        if (result2 != null)
                        {
                            result2.AvailableSeats -= seats;
                            db.SaveChanges();
                        }
                        var passenger = db.Users.Where(x => x.UserName == result.PassengerName).FirstOrDefault();
                        if (passenger != null)
                        {
                            var passEmail = passenger.Email;

                            var message = @String.Format("<div> Your ride reservation request has been accepted !! <br /> " +
                                "Please return to the app and check your reservation status to contact the driver and discuss travel arrangements.. </div>");

                            EmailController email = new EmailController();

                            email.SendEmail(passEmail, "Ride With Me - Reservation Update", message);
                        }
                    }
                    else
                    {
                        TempData["Message"] = "No seats available!!";
                    }
                }
                
            }
            return RedirectToAction("Request",new { Driver = name });
        }
        [Authorize(Roles = "Driver")]
        public ActionResult Decline(int? id, int seats)
        {
            string name = "";
            var result = db.RideReservations.SingleOrDefault(m => m.ReservationID == id);
            if (result != null)
            {
                name = result.DriverName;
                if (result.ReservationStatus == "Accepted")
                {
                    var result2 = db.Rides.SingleOrDefault(m => m.RideID == result.RideID);
                    if (result2 != null)
                    {
                        result2.AvailableSeats += seats;
                        db.SaveChanges();
                    }
                }
                result.ReservationStatus = "Declined";
                db.SaveChanges();
                var passenger = db.Users.Where(x => x.UserName == result.PassengerName).FirstOrDefault();
                if (passenger != null)
                {
                    var passEmail = passenger.Email;

                    var message = @String.Format("<div> Sorry, the driver is unable to accomodate your reservation request at the moment.. <br />" +
                        " Don't be discouraged !! </br> You may return to the app and search for other rides.. </div>");

                    EmailController email = new EmailController();

                    email.SendEmail(passEmail, "Ride With Me - Reservation Update", message);
                }
            }
            return RedirectToAction("Request", new { Driver = name });
        }



        // GET: RideReservations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RideReservation rideReservation = db.RideReservations.Find(id);
            if (rideReservation == null)
            {
                return HttpNotFound();
            }
            return View(rideReservation);
        }

        // GET: RideReservations/Create
        public ActionResult Create()
        {
            RideReservation obj = new RideReservation();
            return View(obj);
        }

        // POST: RideReservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Passenger")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReservationID,RideID,DriverName,PassengerName,SeatsRequired,ReservationStatus")] RideReservation rideReservation)
        {
            if (ModelState.IsValid)
            {
                db.RideReservations.Add(rideReservation);
                db.SaveChanges();
                TempData["Message"] = "Reservation request successfully submitted!!";
                var driver = db.Users.Where(x => x.UserName == rideReservation.DriverName).FirstOrDefault();
                if (driver != null)
                {
                    var drvEmail = driver.Email;

                    var message = @String.Format("<div> You have a new ride reservation request <br />" +
                    "</br> Please return to the application to manage them. </div>");

                    EmailController email = new EmailController();

                    email.SendEmail(drvEmail, "Ride With Me - New Reservation Request", message);
                }

                return RedirectToAction("Index","Home");
            }

            return View(rideReservation);
        }

        // GET: RideReservations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RideReservation rideReservation = db.RideReservations.Find(id);
            if (rideReservation == null)
            {
                return HttpNotFound();
            }
            return View(rideReservation);
        }

        // POST: RideReservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReservationID,RideID,DriverName,PassengerName,SeatsRequired,ReservationStatus")] RideReservation rideReservation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rideReservation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }
            return View(rideReservation);
        }

        // GET: RideReservations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RideReservation rideReservation = db.RideReservations.Find(id);
            if (rideReservation == null)
            {
                return HttpNotFound();
            }
            return View(rideReservation);
        }

        // POST: RideReservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RideReservation rideReservation = db.RideReservations.Find(id);
            db.RideReservations.Remove(rideReservation);
            db.SaveChanges();
            TempData["Message"] = "Reservation successfully deleted!!";
            return RedirectToAction("Index","Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/RidesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ridewithme.Models;

namespace Ridewithme.Controllers
{
    [Authorize]
    public class RidesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Rides
        public ActionResult Index()
        {
            return View(db.Rides.ToList());
        }

        // GET: Rides/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ride ride = db.Rides.Find(id);
            if (ride == null)
            {
                return HttpNotFound();
            }
            return View(ride);
        }

        public ActionResult Search(string start, string destination)
        {
            if (string.IsNullOrEmpty(start) || string.IsNullOrEmpty(destination))
            {
                TempData["Message"] = "Please enter valid start and destination locations!!";
                return RedirectToAction("Index", "Home");
            }
            return View(db.Rides.Where(f => f.Type == 0 && f.Origin.Contains(start) || f.Destination.Contains(destination)).ToList());
        }

        public ActionResult MyRides(string username)
        {    
            return View(db.Rides.Where(f => f.Type == 0 && f.UserName == username).ToList());
        }

        public ActionResult Offers()
        {
            return View(db.Rides.Where(x => x.Type == 0).ToList());
        }

        public ActionResult Requests()
        {
            return View(db.Rides.Where(x => x.Type != 0).ToList());
        }

        public ActionResult CreateRideRequest()
        {
            Ride ride = new Ride();
            return View(ride);
        }

        // POST: Rides/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateRideRequest([Bind(Include = "RideID,Type,Origin,Destination,Schedule,Occurance,VehicleType,Model,Color,AirConditioned,AvailableSeats,Contribution,Message,ContactNumber,IsNonSmoking,IsMaleOnly,IsFemaleOnly,DateAdded,UserName")] Ride ride)
        {
            if (ModelState.IsValid)
            {
                db.Rides.Add(ride);
                db.SaveChanges();
                TempData["Message"] = "Ride Request Successfully Saved!!";
                return RedirectToAction("Index", "Home");
            }

            return View(ride);
        }

        // GET: Rides/Create
        public ActionResult Create()
        {
            Ride ride = new Ride();
            return View(ride);
        }

        // POST: Rides/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RideID,Type,Origin,Destination,Schedule,Occurance,VehicleType,Model,Color,AirConditioned,AvailableSeats,Contribution,Message,ContactNumber,IsNonSmoking,IsMaleOnly,IsFemaleOnly,DateAdded,UserName")] Ride ride)
        {
            if (ModelState.IsValid)
            {
                db.Rides.Add(ride);
                db.SaveChanges();
                TempData["Message"] = "Ride Successfully Saved!!";
                return RedirectToAction("Index", "Home");
            }

            return View(ride);
        }

        // GET: Rides/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ride ride = db.Rides.Find(id);
            if (ride == null)
            {
                return HttpNotFound();
            }
            return View(ride);
        }

        // POST: Rides/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RideID,Type,Origin,Destination,Schedule,Occurance,VehicleType,Model,Color,AirConditioned,AvailableSeats,Contribution,Message,ContactNumber,IsNonSmoking,IsMaleOnly,IsFemaleOnly,DateAdded,UserName")] Ride ride)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ride).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Message"] = "Ride Successfully Updated!!";
                return RedirectToAction("Index", "Home");
            }
            return View(ride);
        }

        // GET: Rides/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ride ride = db.Rides.Find(id);
            if (ride == null)
            {
                return HttpNotFound();
            }
            return View(ride);
        }

        // POST: Rides/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ride ride = db.Rides.Find(id);
            db.Rides.Remove(ride);
            db.SaveChanges();
            TempData["Message"] = "Ride Successfully Deleted!!";
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/TrafficController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ridewithme.Controllers
{
    public class TrafficController : Controller
    {
        // GET: Traffic
        public ActionResult Updates()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - RideWithMe </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <script>
        document.onreadystatechange = function () {
            var state = document.readyState
            if (state == 'complete') {
                document.getElementById('interactive');
                document.getElementById('load').style.visibility = "hidden";
            }
        }
    </script>

    <style>
        #load {
            width: 100%;
            height: 100%;
            position: absolute;
            z-index: 999;
            background: url(../../Content/copper-loader.gif) no-repeat fixed center;
            opacity:0.9;
        }
    </style>


</head>
<body>
    <div id="load"></div>
    <style>
        .dropdown-item:hover, .dropdown-item:focus {
            color: #ffffff;
            text-decoration: none;
            background-color: #000000;
        }
    </style>
    <div>
        <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand text-warning" href="@Url.Action("Index", "Home")"><img src="~/Content/logo.png" width="100" height="25" /> <img src="~/Content/icons8-color-48.png" height="30" /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-success" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-car-side"></i> Rides
                        </a>
                        <div class="dropdown-menu" caria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Offers", "Rides")">Ride Offers</a>


                            @using Microsoft.AspNet.Identity
                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.IsInRole("Driver"))
                                {
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="@Url.Action("Requests", "Rides")">Ride Requests</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="@Url.Action("Create", "Rides")">Add Rides</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="@Url.Action("MyRides", "Rides", new {Username = User.Identity.GetUserName()})"> My Rides</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="@Url.Action("Request", "RideReservations", new { Driver = User.Identity.GetUserName() })"> Manage Reservations Request </a>
                                }
                                if (User.IsInRole("Passenger"))
                                {
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="@Url.Action("CreateRideRequest", "Rides")">Add Ride Request</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="@Url.Action("Status", "RideReservations", new { Passenger = User.Identity.GetUserName() })"> Check Reservations Status </a>
                                }
                            }
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-danger" href="@Url.Action("Updates", "Traffic")"><i class="fas fa-traffic-light"></i> Traffic Updates</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-warning" href="#" data-toggle="modal" data-target="#myModal"><i class="fas fa-gas-pump"></i> Fuel Cost Calculator</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-info" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-info-circle"></i> About
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("About", "Home")">Project Information</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("Contact", "Home")">Contact Developer</a>
                        </div>

                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </nav>
    </div>
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content bg-light">
                <div class="modal-header text-center">
                    <h4 class="modal-title white-text w-100 font-weight-bold py-2">Fuel Cost Calculator</h4>
                </div>
                <div class="modal-body justify-content-center">
                    <div class="row">
                        <div class="col-4"> <strong> Trip Distance</strong> </div>
                        <div class="col-5"> @Html.TextBox("TripDistance", null, new { @class = "form-control", @type = "number", min = 0 }) </div>
                        <div class="col-3"> Km(s)</div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-4"> <strong> Passengers </strong> </div>
                        <div class="col-5"> @Html.TextBox("Passengers", 0, new { @class = "form-control", @type = "number", min = 0 }) </div>
                        <div class="col-3"> Person(s) </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-4"> <strong> Fuel Efficency </strong>  </div>
                        <div class="col-5"> @Html.TextBox("FuelEfficency", null, new { @class = "form-control", @type = "number", min = 0 }) </div>
                        <div class="col-3"> Km(s)/Ltr </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-4"> <strong> Fuel Type </strong> </div>
                        <div class="col-5">
                            @*@Html.DropDownList("FuelType", (IEnumerable
                                <SelectListItem>)ViewData["FuelList"])*@

                            @Html.DropDownList("FuelType", new List<SelectListItem>{
                                new SelectListItem { Value = "137" , Text = "Petrol 92" },
                                new SelectListItem { Value = "161" , Text = "Petrol 95" },
                                new SelectListItem { Value = "104" , Text = "Auto Diesel" },
                                new SelectListItem { Value = "132" , Text = "Super Diesel" }}, new { @class = "form-control" })
                        </div>
                    </div>
                    <hr />
                    <div class="row justify-content-center">
                        <div class="col-4"> <input type="checkbox" id="withAC">  <strong> With A/C </strong> </div>
                        <div class="col-4"> <input type="checkbox" id="roundTrip"> <strong> Round Trip </strong> </div>

                    </div>
                    <hr />
                    <div class="text-center">
                        <label class="text-success" id="outputlabel"> </label>
                        <br />
                        <label class="text-info" id="outputlabel2"> </label>
                        <br />
                    </div>

                </div>
                <div class="modal-footer justify-content-center">

                    <button onclick="CalculateFuelCost()" class="btn btn-outline-primary" type="button"> Calculate </button>

                    <button onclick="ClearLabel()" type="button" class="btn btn-outline-danger" data-dismiss="modal"> Close</button>

                </div>

            </div>
        </div>

    </div>


    <script>

            function CalculateFuelCost() {

                //get values from user
                var tripDistance = parseInt(document.getElementById('TripDistance').value);
                var fuelEfficency = parseInt(document.getElementById('FuelEfficency').value);
                var fuelPrice = parseInt(document.getElementById('FuelType').value);
                var passengers = parseInt(document.getElementById('Passengers').value);
                var checkBox1 = document.getElementById("withAC");
                var checkBox2 = document.getElementById("roundTrip");

                // perform calculations
                var nFuelEfficency = fuelEfficency - (passengers * 0.5);
                var FuelCost = ((tripDistance / nFuelEfficency) * fuelPrice).toFixed(0);
                var FuelCostAC = ((tripDistance / (nFuelEfficency - 2)) * fuelPrice).toFixed(0);
                var FuelCostRT = FuelCost * 2;
                var FuelCostACRT = FuelCostAC * 2;
                var Contribution = (FuelCost / (passengers + 1)).toFixed(0);
                var ContributionAC = (FuelCostAC / (passengers + 1)).toFixed(0);
                var ContributionRT = Contribution * 2;
                var ContributionACRT = ContributionAC * 2;

                if (isNaN(FuelCost)) {
                    document.getElementById('outputlabel').innerHTML = "Please enter valid parameters!!";
                }
                else if (checkBox1.checked == true && checkBox2.checked == true) {
                    document.getElementById('outputlabel').innerHTML = "Estimated Fuel Cost is " + "Rs. " + FuelCostACRT + " /-";
                    if (passengers != 0) {
                        document.getElementById('outputlabel2').innerHTML = "Passenger Contribution " + "Rs. " + ContributionACRT + " /-";
                    }
                }
                else if (checkBox1.checked == true && checkBox2.checked == false) {
                    document.getElementById('outputlabel').innerHTML = "Estimated Fuel Cost is " + "Rs. " + FuelCostAC + " /-";
                    if (passengers != 0) {
                        document.getElementById('outputlabel2').innerHTML = "Passenger Contribution " + "Rs. " + ContributionAC + " /-";
                    }
                }
                else if (checkBox1.checked == false && checkBox2.checked == true) {
                    document.getElementById('outputlabel').innerHTML = "Estimated Fuel Cost is " + "Rs. " + FuelCostRT + " /-";
                    if (passengers != 0) {
                        document.getElementById('outputlabel2').innerHTML = "Passenger Contribution " + "Rs. " + ContributionRT + " /-";
                    }
                }
                else {
                    document.getElementById('outputlabel').innerHTML = "Estimated Fuel Cost is " + "Rs. " + FuelCost + " /-";
                    if (passengers != 0) {
                        document.getElementById('outputlabel2').innerHTML = "Passenger Contribution " + "Rs. " + Contribution + " /-";
                    }
                }
            }
            function ClearLabel() {
                document.getElementById('outputlabel').innerHTML = "";
                document.getElementById('outputlabel2').innerHTML = "";
                document.getElementById('TripDistance').value = "";
                document.getElementById('FuelEfficency').value = "";
                document.getElementById('Passengers').value = 0;
                document.getElementById("withAC").checked = false;
                document.getElementById("roundTrip").checked = false;
            }

        </script>




    <div class="container body-content">
        @RenderBody()

        <hr />

        <footer>
            <nav class="navbar rounded navbar-dark bg-dark text-light text-center">
                <div class="mx-md-auto"> Copyright &copy 2019 RideWithMe - All Rights Reserved </div>
            </nav>
        </footer>
    </div>


    @Scripts.Render("~/bundles/lib")
    @Styles.Render("~/Content/font-awesome")
    @RenderSection("scripts", required: false)
</body>
</html>
